name: Build

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2022
    env:
      BOOST_ROOT: C:/tools/boost/x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install boost-msvc-14.3 --version=1.82.0
          choco install qt5 --version=5.15.2

      - name: Clone fuego
        run: |
          Remove-Item -Recurse -Force cryptonote -ErrorAction SilentlyContinue
          git clone https://github.com/colinritman/fuego.git cryptonote

      - name: Download STARK CLI from colinritman/xfgwin release
        run: |
          # Get the latest release info
          $releaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/ColinRitman/xfgwin/releases/latest"
          $asset = $releaseInfo.assets | Where-Object { $_.name -eq "xfg-stark-cli-windows.tar.gz" }
          $downloadUrl = $asset.browser_download_url
          
          Write-Host "Downloading STARK CLI from: $downloadUrl"
          
          # Download and extract the binary
          Invoke-WebRequest -Uri $downloadUrl -OutFile "xfg-stark-cli-windows.tar.gz"
          tar -xzf xfg-stark-cli-windows.tar.gz
          
          # Verify the binary works
          .\xfg-stark-cli.exe --version
          
          Write-Host "✅ STARK CLI downloaded and verified successfully"

      - name: Build
        id: build
        run: |
          $xfgVer = $env:GITHUB_REF -replace "refs/tags/", ""
          $releaseName = "fuego-desktop-windows-v$xfgVer"
          $appName = "Fuego-Wallet.exe"

          # Clean up any existing CMake cache files
          Remove-Item -Force CMakeCache.txt -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          
          # Build using CMake (main project, not cryptonote subdirectory)
          New-Item -ItemType Directory -Path "build\release" -Force
          Set-Location "build\release"
          cmake ..\..
          cmake --build . --config Release --parallel 4
          Set-Location ..\..
          
          Set-Location "build\release"
          windeployqt "$appName"
          cpack
          New-Item -ItemType Directory -Path "$releaseName" -Force
          New-Item -ItemType Directory -Path "$releaseName\tools" -Force
          Move-Item "*.exe" "$releaseName\"
          # Include STARK CLI in release
          Copy-Item "..\..\xfg-stark-cli.exe" "$releaseName\tools\"
          Copy-Item "..\..\download-stark-cli.sh" "$releaseName\tools\"
          Copy-Item "..\..\scripts\auto_stark_proof.sh" "$releaseName\tools\"
          Copy-Item "..\..\STARK_CLI_INTEGRATION_OPTIMIZATION.md" "$releaseName\"
          Compress-Archive -Path "$releaseName", "*.exe" -DestinationPath "$releaseName.zip"
          $sha256 = (Get-FileHash "$releaseName.zip" -Algorithm SHA256).Hash.ToUpper()

          echo "sha256=$sha256" >> $env:GITHUB_OUTPUT
          echo "release_name=$releaseName.zip" >> $env:GITHUB_OUTPUT
          echo "asset_path=build\release\$releaseName.zip" >> $env:GITHUB_OUTPUT
          echo "xfg_version=$xfgVer" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego Desktop v${{ steps.build.outputs.xfg_ver }}
          body: |
            <img src="https://cdn-icons-png.flaticon.com/512/882/882602.png" width="16"> [Download for Windows](../../releases/download/${{ steps.build.outputs.xfg_ver }}/${{ steps.build.outputs.release_name }}) ${{ steps.build.outputs.release_name }}
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu22:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev pkg-config libqt5widgets5 libqt5gui5 libqt5core5a libqt5charts5-dev libqt5svg5-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqrencode-dev

      - name: Clone fuego
        run: |
          rm -rf cryptonote
          git clone https://github.com/colinritman/fuego.git cryptonote

      - name: Download STARK CLI from colinritman/xfgwin release
        run: |
          # Get the latest release info
          RELEASE_URL=$(curl -s https://api.github.com/repos/ColinRitman/xfgwin/releases/latest | jq -r '.assets[] | select(.name=="xfg-stark-cli-linux.tar.gz") | .browser_download_url')
          
          echo "Downloading STARK CLI from: $RELEASE_URL"
          
          # Download and extract the binary
          curl -L -o xfg-stark-cli-linux.tar.gz "$RELEASE_URL"
          tar -xzf xfg-stark-cli-linux.tar.gz
          
          # Make binary executable
          chmod +x xfg-stark-cli
          
          # Verify the binary works
          ./xfg-stark-cli --version
          
          echo "✅ STARK CLI downloaded and verified successfully"

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          xfg_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="fuego-desktop-ubuntu22-v$xfg_ver"
          app_name="FuegoWallet"

          # Clean up any existing CMake cache files
          rm -f CMakeCache.txt CMakeCache.txt.*
          rm -rf build/
          
          # Build using CMake (main project, not cryptonote subdirectory)
          mkdir -p build/release
          cd build/release
          cmake ../..
          make -j4
          cd ../..
          
          cd build/release
          mkdir "$release_name"
          mkdir -p "$release_name/tools"
          cp "$app_name" "$release_name/"
          # Include STARK CLI in release
          cp ../../xfg-stark-cli "$release_name/tools/"
          cp ../../download-stark-cli.sh "$release_name/tools/"
          cp ../../scripts/auto_stark_proof.sh "$release_name/tools/"
          cp ../../STARK_CLI_INTEGRATION_OPTIMIZATION.md "$release_name/"
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(sha256sum "$release_name".tar.gz | awk '{ print toupper($1) }')

          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "asset_path=build/release/${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "xfg_version=${xfg_version}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego Desktop v${{ steps.build.outputs.xfg_ver }}
          body: |
            <img src="https://cdn-icons-png.flaticon.com/512/882/882602.png" width="16"> [Download for Ubuntu 22.04](../../releases/download/${{ steps.build.outputs.xfg_ver }}/${{ steps.build.outputs.release_name }}) ${{ steps.build.outputs.release_name }}
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-ubuntu24:
    name: Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev libssl-dev pkg-config libqt5widgets5 libqt5gui5 libqt5core5a libqt5charts5-dev libqt5svg5-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqrencode-dev

      - name: Clone fuego
        run: |
          rm -rf cryptonote
          git clone https://github.com/colinritman/fuego.git cryptonote

      - name: Download STARK CLI from colinritman/xfgwin release
        run: |
          # Get the latest release info
          RELEASE_URL=$(curl -s https://api.github.com/repos/ColinRitman/xfgwin/releases/latest | jq -r '.assets[] | select(.name=="xfg-stark-cli-linux.tar.gz") | .browser_download_url')
          
          echo "Downloading STARK CLI from: $RELEASE_URL"
          
          # Download and extract the binary
          curl -L -o xfg-stark-cli-linux.tar.gz "$RELEASE_URL"
          tar -xzf xfg-stark-cli-linux.tar.gz
          
          # Make binary executable
          chmod +x xfg-stark-cli
          
          # Verify the binary works
          ./xfg-stark-cli --version
          
          echo "✅ STARK CLI downloaded and verified successfully"

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          xfg_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="fuego-desktop-ubuntu24-v$xfg_ver"
          app_name="FuegoWallet"

          # Clean up any existing CMake cache files
          rm -f CMakeCache.txt CMakeCache.txt.*
          rm -rf build/
          
          # Build using CMake (main project, not cryptonote subdirectory)
          mkdir -p build/release
          cd build/release
          cmake ../..
          make -j4
          cd ../..
          
          cd build/release
          mkdir "$release_name"
          mkdir -p "$release_name/tools"
          cp "$app_name" "$release_name/"
          # Include STARK CLI in release
          cp ../../xfg-stark-cli "$release_name/tools/"
          cp ../../download-stark-cli.sh "$release_name/tools/"
          cp ../../scripts/auto_stark_proof.sh "$release_name/tools/"
          cp ../../STARK_CLI_INTEGRATION_OPTIMIZATION.md "$release_name/"
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(sha256sum "$release_name".tar.gz | awk '{ print toupper($1) }')

          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "asset_path=build/release/${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "xfg_version=${xfg_version}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego Desktop v${{ steps.build.outputs.xfg_ver }}
          body: |
            <img src="https://cdn-icons-png.flaticon.com/512/882/882602.png" width="16"> [Download for Ubuntu 24.04](../../releases/download/${{ steps.build.outputs.xfg_ver }}/${{ steps.build.outputs.release_name }}) ${{ steps.build.outputs.release_name }}
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-intel:
    name: macOS Intel
    runs-on: macos-13  # Intel runner
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install boost qt@5

      - name: Clone fuego
        run: |
          rm -rf cryptonote
          git clone https://github.com/colinritman/fuego.git cryptonote

      - name: Download STARK CLI from colinritman/xfgwin release
        run: |
          # Get the latest release info
          RELEASE_URL=$(curl -s https://api.github.com/repos/ColinRitman/xfgwin/releases/latest | jq -r '.assets[] | select(.name=="xfg-stark-cli-macos.tar.gz") | .browser_download_url')
          
          echo "Downloading STARK CLI from: $RELEASE_URL"
          
          # Download and extract the binary
          curl -L -o xfg-stark-cli-macos.tar.gz "$RELEASE_URL"
          tar -xzf xfg-stark-cli-macos.tar.gz
          
          # Make binary executable
          chmod +x xfg-stark-cli
          
          # Verify the binary works
          ./xfg-stark-cli --version
          
          echo "✅ STARK CLI downloaded and verified successfully"

      - name: Build
        id: build
        run: |
          export PATH="/usr/local/opt/qt@5/bin:$PATH"
          build_folder="build/release"
          xfg_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="fuego-desktop-macOS-intel-v$xfg_ver"
          app_name="Fuego-Wallet.app"

          # Clean up any existing CMake cache files
          rm -f CMakeCache.txt CMakeCache.txt.*
          rm -rf build/
          
          # Build using CMake (main project, not cryptonote subdirectory)
          mkdir -p build/release
          cd build/release
          cmake ../..
          make -j4
          cd ../..
          
          cd build/release
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mkdir -p "$release_name/tools"
          mv *.dmg "$release_name".dmg
          # Include STARK CLI in release
          cp ../../xfg-stark-cli "$release_name/tools/"
          cp ../../download-stark-cli.sh "$release_name/tools/"
          cp ../../scripts/auto_stark_proof.sh "$release_name/tools/"
          cp ../../STARK_CLI_INTEGRATION_OPTIMIZATION.md "$release_name/"
          zip "$release_name".zip "$release_name".dmg "$release_name/tools" "$release_name/STARK_CLI_INTEGRATION_OPTIMIZATION.md"
          sha256=$(shasum -a 256 "$release_name".zip | awk '{ print toupper($1) }')

          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.zip" >> $GITHUB_OUTPUT
          echo "asset_path=build/release/${release_name}.zip" >> $GITHUB_OUTPUT
          echo "xfg_version=${xfg_version}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego Desktop v${{ steps.build.outputs.xfg_ver }}
          body: |
            <img src="https://cdn-icons-png.flaticon.com/512/882/882602.png" width="16"> [Download for macOS Intel](../../releases/download/${{ steps.build.outputs.xfg_ver }}/${{ steps.build.outputs.release_name }}) ${{ steps.build.outputs.release_name }}
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos-apple-silicon:
    name: macOS Apple Silicon
    runs-on: macos-14  # Apple Silicon runner
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install boost qt@5

      - name: Clone fuego
        run: |
          rm -rf cryptonote
          git clone https://github.com/colinritman/fuego.git cryptonote

      - name: Download STARK CLI from colinritman/xfgwin release
        run: |
          # Get the latest release info
          RELEASE_URL=$(curl -s https://api.github.com/repos/ColinRitman/xfgwin/releases/latest | jq -r '.assets[] | select(.name=="xfg-stark-cli-macos.tar.gz") | .browser_download_url')
          
          echo "Downloading STARK CLI from: $RELEASE_URL"
          
          # Download and extract the binary
          curl -L -o xfg-stark-cli-macos.tar.gz "$RELEASE_URL"
          tar -xzf xfg-stark-cli-macos.tar.gz
          
          # Make binary executable
          chmod +x xfg-stark-cli
          
          # Verify the binary works
          ./xfg-stark-cli --version
          
          echo "✅ STARK CLI downloaded and verified successfully"

      - name: Build
        id: build
        run: |
          export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
          build_folder="build/release"
          xfg_ver=$(echo ${{ github.ref }} | sed 's|refs/tags/||')
          release_name="fuego-desktop-macOS-apple-silicon-v$xfg_ver"
          app_name="Fuego-Wallet.app"

          # Clean up any existing CMake cache files
          rm -f CMakeCache.txt CMakeCache.txt.*
          rm -rf build/
          
          # Build using CMake (main project, not cryptonote subdirectory)
          mkdir -p build/release
          cd build/release
          cmake ../..
          make -j4
          cd ../..
          
          cd build/release
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mkdir -p "$release_name/tools"
          mv *.dmg "$release_name".dmg
          # Include STARK CLI in release
          cp ../../xfg-stark-cli "$release_name/tools/"
          cp ../../download-stark-cli.sh "$release_name/tools/"
          cp ../../scripts/auto_stark_proof.sh "$release_name/tools/"
          cp ../../STARK_CLI_INTEGRATION_OPTIMIZATION.md "$release_name/"
          zip "$release_name".zip "$release_name".dmg "$release_name/tools" "$release_name/STARK_CLI_INTEGRATION_OPTIMIZATION.md"
          sha256=$(shasum -a 256 "$release_name".zip | awk '{ print toupper($1) }')

          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.zip" >> $GITHUB_OUTPUT
          echo "asset_path=build/release/${release_name}.zip" >> $GITHUB_OUTPUT
          echo "xfg_version=${xfg_version}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v4
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Fuego Desktop v${{ steps.build.outputs.xfg_ver }}
          body: |
            <img src="https://cdn-icons-png.flaticon.com/512/882/882602.png" width="16"> [Download for macOS Apple Silicon](../../releases/download/${{ steps.build.outputs.xfg_ver }}/${{ steps.build.outputs.release_name }}) ${{ steps.build.outputs.release_name }}
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
