name: Build check test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:

jobs:
  build-ubuntu20:
    name: Ubuntu 20.04
    runs-on: self_ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update -y
          apt install -y qt5-default qttools5-dev qttools5-dev-tools libqt5charts5-dev libboost-all-dev git

      - name: Clone fuego
        run: |
          rm -rf cryptonote
          git clone https://github.com/usexfg/fuego.git cryptonote

      - name: Build
        id: build
        run: |
          xfg_version=${GITHUB_SHA::7}
          release_name=fuego-desktop-ubuntu-2004-dev-"$xfg_version"

          make -j4 build-release
          mkdir $release_name
          mkdir -p $release_name/icon
          mv build/release/
          -Wallet $release_name
          cp fuego-desktop.desktop $release_name
          cp src/images/fuego.png $release_name/icon
          tar -czf "$release_name".tar.gz "$release_name"

          echo "release_name=${release_name}" >> $GITHUB_OUTPUT
          echo "artifact_path=${release_name}.tar.gz" >> $GITHUB_OUTPUT

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
