name: Build check test

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:

jobs:
  build-ubuntu18:
    name: Ubuntu 18.04
    runs-on: self_ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt update -y
          apt install -y qt5-default qttools5-dev qttools5-dev-tools libqt5charts5-dev libboost-all-dev git

      - name: Clone fango
        run: |
          rm -rf cryptonote
          git clone https://github.com/fandomgold/fango.git cryptonote

      - name: Build
        id: build
        run: |
          xfg_version=${GITHUB_SHA::7}
          release_name=fango-desktop-ubuntu-1804-dev-"$xfg_version"

          make -j4 build-release
          mkdir $release_name
          mkdir -p $release_name/icon
          mv build/release/Fango-Wallet $release_name
          cp fango-desktop.desktop $release_name
          cp src/images/fango.png $release_name/icon
          tar -czf "$release_name".tar.gz "$release_name"

          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=artifact_path::$release_name.tar.gz"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
